version: "3"
services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc@123
    networks:
      - backend

  redis:
    image: "redis:5.0-alpine"
    container_name: redis
    networks:
      - backend
volumes:
  db_data:
networks:
  backend:
